### PR TITLE
add wildcard support to map notifications

### PR DESCRIPTION
**Pull request by Trevor159**
comment here or @ Trevor#3815 in disc for questions

### CODE REVIEW

**Comment by Vauff** [comment]
Thanks for the contribution! Only minor change I would suggest it to move the wildcardMatches() stuff into ServerTimerThread itself. I generally put things in Util when they're referenced in multiple places.

**Comment by Trevor159** [comment]
> Thanks for the contribution! Only minor change I would suggest is to move the wildcardMatches() stuff into ServerTimerThread itself. I generally put things in Util when they're referenced by multiple classes.

done, I also added a break so people can't be messages multiple times for the same map

**Comment by Vauff** [comment]
You'll want `continue` instead of `break`, because with break it will stop iterating notification files entirely as soon as one persons notification is found.

**Comment by Vauff** [comment]
Logic seems busted in some way, I'm receiving notifications for every map change when I have at least one map notification added.

**Comment by Trevor159** [comment]
> Logic seems busted in some way, I'm receiving notifications for every map change when I have at least one map notification added.

hmm, I can test more

**Comment by Trevor159** [comment]
big face palm, the logic was correct but I added a semicolon after the if statement so it effectively bypassed it. I must have done that on accident after I tested it.

**Pull request merged**
