### PR TITLE
Improve system to confirm messages via reactions

### PR DESCRIPTION
**Pull request by bl4ckscor3**
A command can now be set to await a confirmation by calling `waitForConfirmation(messageID)` where messageID is the string id of the message that is supposed to await a confirmation. When the user adds a reaction to said message, it checks wether the message has been confirmed or denied, calls the respective method of the command the confirmable message got sent by and deletes the initial message.

This system currently allows for only ✅ and ❌ to be handled, but I can add a method that gets called for every other Emoji if you so desire.
The option to have multiple messages confirmable from one command execution is also possible, just add more messages using `AbstractCommand#waitForConfirmation`.

### CODE REVIEW

**Comment by Vauff** [comment]
This looks pretty good, I will suggest a rename of the confirm and deny AbstractCommand methods to whiteHeavyCheckMarkReaction and crossMarkReaction though. As it makes more sense to use direct emoji names for further expansion of the feature for new reactions in other commands.

**Comment by Vauff** [comment]
And in the same vain, rename waitForConfirmation to waitForReaction.

**Comment by bl4ckscor3** [comment]
I have a different idea. The way you plan to extend with methods would mean to add the emojis to the if checks in `MainListener#onReactionAdd` as well as within `AbstractCommand`. What about an `AbstractCommand#confirmable` method that switches between having to confirm/deny a message and generally handling a reaction? I can push a commit to show you what I mean.

**Comment by Vauff** [comment]
Sure, you can push that then and I'll take a look.

**Pull request merged**
